// hero article
export const GET_HERO_ARTICLE_REQUEST = 'GET_HERO_ARTICLE_REQUEST';
export const GET_HERO_ARTICLE_SUCCESS = 'GET_HERO_ARTICLE_SUCCESS';
export const GET_HERO_ARTICLE_FAILURE = 'GET_HERO_ARTICLE_FAILURE';

export const GET_LIST_ARTICLE = 'GET_LIST_ARTICLE';
export const GET_LIST_ARTICLE_SUCCESS = 'GET_LIST_ARTICLE_SUCCESS';
export const GET_LIST_ARTICLE_FAILURE = 'GET_LIST_ARTICLE_FAILURE';

export const GET_POPULAR_TAGS = 'GET_POPULAR_TAGS';
export const GET_POPULAR_TAGS_SUCCESS = 'GET_POPULAR_TAGS_SUCCESS';
export const GGET_POPULAR_TAGS_FAILURE = 'GGET_POPULAR_TAGS_FAILURE';
