export const REPORT_SUCCESS = 'REPORT_SUCCESS';
export const REPORT_FAILURE = 'REPORT_FAILURE';
export const REPORT_POSTING = 'REPORT_POSTING';
export const INITIALIZE_REPORT = 'INITIALIZE_REPORT';
export const REPORT_ERROR_CLEARED = 'REPORT_ERROR_CLEARED';
